language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - sudo apt-get install mcrypt php5-mcrypt
  - sudo php5enmod mcrypt
  - sudo service apache2 restart

before_script:
  - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
